spring.application.name=ewm-main-service
server.port=0
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm
spring.datasource.username=dbuser
spring.datasource.password=12345
stat-client.timeout-ms=1000
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5
stat-server.service-id=stats-server