spring.application.name=collector-service

# gRPC: 0 = ????????? ????, ????????? ??; ???????? ???? ??????????? ? Eureka
# ????? ru.practicum.ewm.stats.collector.config.GrpcPortInitializer (??. ????? 3)
grpc.server.port=0

# --- Kafka producer ---
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.value-serializer=ru.practicum.ewm.stats.avro.serializer.UserActionSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.linger.ms=10

# ?????, ? ??????? Collector ????????? ???????? ?????????????
collector.kafka.topic.user-actions=stats.user-actions.v1

# --- Config Server / Eureka ---
spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5