spring.application.name=request-service
server.port=0

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-requests
spring.datasource.username=dbuser
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

spring.config.import=optional:configserver:

spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5

feign.client.config.default.connect-timeout=3000
feign.client.config.default.read-timeout=5000

# ===== Resilience4j CircuitBreaker =====
resilience4j.circuitbreaker.instances.user-client.sliding-window-size=20
resilience4j.circuitbreaker.instances.user-client.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.user-client.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.user-client.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.user-client.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.user-client.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.user-client.ignore-exceptions=ewm.request.server.exception.NotFoundException

resilience4j.circuitbreaker.instances.event-client.sliding-window-size=10
resilience4j.circuitbreaker.instances.event-client.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.event-client.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.event-client.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.event-client.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.event-client.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.event-client.ignore-exceptions=ewm.request.server.exception.NotFoundException

resilience4j.retry.instances.user-client.max-attempts=3
resilience4j.retry.instances.user-client.wait-duration=200ms
resilience4j.retry.instances.user-client.ignore-exceptions=ewm.request.server.exception.NotFoundException,feign.FeignException$NotFound

resilience4j.retry.instances.event-client.max-attempts=3
resilience4j.retry.instances.event-client.wait-duration=200ms
resilience4j.retry.instances.event-client.ignore-exceptions=ewm.request.server.exception.NotFoundException,feign.FeignException$NotFound