services:

  discovery-server:
    build: infra/discovery-server
    image: discovery-server
    ports:
      - "8761:8761"

  config-server:
    build: infra/config-server
    image: config-server
    depends_on:
      discovery-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  gateway-server:
    build: infra/gateway-server
    image: gateway-server
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
      ewm-service:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=true
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICE_ID=config-server

  stats-server:
    build: stat/stat-server
    image: stat-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=true
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICE_ID=config-server

  stats-db:
    image: postgres:16.1

  ewm-service:
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: main-service
    image: ewm-service
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/8080' || exit 1" ]
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 10s
    depends_on:
      ewm-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=true
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICE_ID=config-server

  ewm-db:
    image: postgres:16.1
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

