spring.application.name=discovery-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.enable-self-preservation=false

eureka.server.use-read-only-response-cache=false
eureka.server.response-cache-update-interval-ms=1000