spring.application.name=analyzer-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-analyzer
spring.datasource.username=analyzer
spring.datasource.password=analyzer

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

grpc.server.port=0

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=analyzer

analyzer.kafka.topic.user-actions=stats.user-actions.v1
analyzer.kafka.topic.events-similarity=stats.events-similarity.v1

analyzer.weights.view=0.4
analyzer.weights.register=0.8
analyzer.weights.like=1.0

analyzer.recommendations.recent-interactions-limit=10
analyzer.recommendations.neighbors-count=3

spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5