CREATE TABLE IF NOT EXISTS user_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    action_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_user_actions PRIMARY KEY (id),
    CONSTRAINT uq_user_actions_user_event UNIQUE (user_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_user_actions_event ON user_actions (event_id);
CREATE INDEX IF NOT EXISTS idx_user_actions_user_timestamp ON user_actions (user_id, action_timestamp DESC);

CREATE TABLE IF NOT EXISTS event_similarities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_a BIGINT NOT NULL,
    event_b BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    similarity_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_event_similarities PRIMARY KEY (id),
    CONSTRAINT uq_event_similarities_pair UNIQUE (event_a, event_b)
);

CREATE INDEX IF NOT EXISTS idx_event_similarities_event_a ON event_similarities (event_a);
CREATE INDEX IF NOT EXISTS idx_event_similarities_event_b ON event_similarities (event_b);